# Generated by Django 5.2.7 on 2026-02-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=120)),
                ('adresa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('aktivan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=120)),
                ('aktivan', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frizeri', to='rezervacije.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('vrijeme_od', models.TimeField()),
                ('vrijeme_do', models.TimeField()),
                ('slobodan', models.BooleanField(default=True)),
                ('frizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termini', to='rezervacije.frizer')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termini', to='rezervacije.salon')),
            ],
            options={
                'ordering': ['datum', 'vrijeme_od'],
            },
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('potvrdena', 'Potvrđena'), ('otkazana', 'Otkazana')], default='potvrdena', max_length=20)),
                ('napomena', models.CharField(blank=True, max_length=250)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacije', to=settings.AUTH_USER_MODEL)),
                ('termin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacija', to='rezervacije.termin')),
            ],
            options={
                'ordering': ['-kreirano'],
            },
        ),
        migrations.AddConstraint(
            model_name='termin',
            constraint=models.UniqueConstraint(fields=('frizer', 'datum', 'vrijeme_od', 'vrijeme_do'), name='jedinstven_termin_po_frizeru'),
        ),
    ]
