# Generated by Django 5.2.7 on 2026-02-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacije', '0003_salon_radno_vrijeme'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='termin',
            constraint=models.CheckConstraint(condition=models.Q(('vrijeme_od__lt', models.F('vrijeme_do'))), name='termin_pocetak_prije_kraja'),
        ),
    ]
